apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 0
  template:
    metadata:
      labels:
        app: busybox
      spec:
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        imagePullPolicy: Always
        command: ["/bin/sleep", "0"]
